# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
cache_gem: &cache_gem
  key: gems-v1-{{ checksum ".circleci/Gemfile.lock" }}

version: 2
jobs:
  test-phpcs:
    docker:
      - image: darh/php-essentials@sha256:b8a26d91f0afd5240ca63bab3d4a935d5894fd9d731d79041b4ec04424a15427
    steps:
      - checkout
      - run: mkdir results
      - run: phpcs --report=checkstyle --report-file=results/phpcs.result.xml --standard=Zend --ignore=vendor . || exit 0
      - run: cat results/phpcs.result.xml
      - persist_to_workspace:
          root: results
          paths:
            - ./*

  test-phpmd:
    docker:
      - image: darh/php-essentials@sha256:b8a26d91f0afd5240ca63bab3d4a935d5894fd9d731d79041b4ec04424a15427
    steps:
      - checkout
      - run: mkdir results
      - run: phpmd . xml codesize,controversial --reportfile results/phpmd.result.xml --exclude vendor || exit 0
      - persist_to_workspace:
          root: results
          paths: 
            - ./*

  report:
    docker:
      - image: circleci/ruby:2.4.2
    steps:
      - checkout
      - run:
          working_directory: .circleci
          command: bundle install
      - attach_workspace:
          at: results
      - run: .circleci/scripts/saddler.sh


workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test-phpcs
      - test-phpmd
      - report:
          context:
            org-global
          requires:
            - test-phpcs
            - test-phpmd
